In [1]:
import cv2
import numpy


In [2]:
image=numpy.ones((500,600,3))

In [3]:
image=cv2.rectangle(image,(0,0),(600,500),(0,180,255),-1)

In [4]:
image.shape

(500, 600, 3)

In [5]:
image=cv2.line(image,(100,50),(300,50),(0,0,255),6)

In [6]:
image=cv2.line(image,(300,50),(300,250),(0,0,255),6)

In [7]:
image=cv2.line(image,(300,250),(480,250),(0,0,255),6)

In [8]:
image=cv2.line(image,(480,50),(480,150),(0,0,25),6)

In [9]:
image=cv2.line(image,(100,150),(480,150),(0,0,255),6)

In [10]:
image=cv2.line(image,(100,150),(100,250),(0,0,255),6)

In [11]:
cv2.circle(image,(200,195),8, (0,0,255), -1)

array([[[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       ...,

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 1

In [12]:
cv2.circle(image,(200,95),8, (0,0,255), -1)

array([[[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       ...,

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 1

In [13]:
cv2.circle(image,(380,195),8, (0,0,255), -1)

array([[[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       ...,

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 1

In [14]:
cv2.circle(image,(380,95),8, (0,0,255), -1)

array([[[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       ...,

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.],
        ...,
        [  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 180., 255.]],

       [[  0., 180., 255.],
        [  0., 180., 255.],
        [  0., 1

In [15]:
cv2.imshow("TASK4.1",image)
cv2.waitKey()
cv2.destroyAllWindows()